name: note_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.13.1
  firebase_storage: ^11.2.2
  firebase_auth: ^4.6.2
  flutter_hooks: ^0.18.6
  uuid: ^3.0.7
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  image_picker: ^0.8.7+5
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
