// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCz5Jc_twceO5wejNCHTlfneTVYgJvPZ3s',
    appId: '1:339694434196:web:49390f65367bd763774181',
    messagingSenderId: '339694434196',
    projectId: 'library-photo-with-bloc',
    authDomain: 'library-photo-with-bloc.firebaseapp.com',
    storageBucket: 'library-photo-with-bloc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRfyr8CdE-JMTdFx-BhLul_wAoHs6X80I',
    appId: '1:339694434196:android:a672143f3f681bf9774181',
    messagingSenderId: '339694434196',
    projectId: 'library-photo-with-bloc',
    storageBucket: 'library-photo-with-bloc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZNBXrjS1f5lhn_W42CbUc2CXSvuCRdGA',
    appId: '1:339694434196:ios:785547302635ebe7774181',
    messagingSenderId: '339694434196',
    projectId: 'library-photo-with-bloc',
    storageBucket: 'library-photo-with-bloc.appspot.com',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZNBXrjS1f5lhn_W42CbUc2CXSvuCRdGA',
    appId: '1:339694434196:ios:a9f4fc910252d053774181',
    messagingSenderId: '339694434196',
    projectId: 'library-photo-with-bloc',
    storageBucket: 'library-photo-with-bloc.appspot.com',
    iosBundleId: 'com.example.noteApp.RunnerTests',
  );
}
